apiVersion: v1
kind: Pod
metadata:
  name: curl-with-ambassador
spec:
  containers:
  - name: main
    image: registry.ty.com/ty/curl
    command: ["sleep", "9999999"]
  - name: ambassador
    image: registry.ty.com/ty/kubectl-proxy:1.6.2
